<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Product>DotMake Docfx-Plus Cli</Product>
    <AssemblyName>docfx-plus</AssemblyName>
    <RollForward>Major</RollForward>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>

    <PackAsTool>true</PackAsTool>
    <ToolCommandName>docfx-plus</ToolCommandName>
    <!-- NuGet Package Information (common ones are in Directory.Build.props) -->
    <!-- Description is used for assembly and NuGet metadata -->
    <Description>A dotnet tool for enhancing docfx behaviour and template/theme.</Description>
    <PackageTags>docfx plus plugin tool template Documentation API Metadata</PackageTags>
    <PackageReleaseNotes>
      <![CDATA[
        - **Added:** New theme property `_enableOfflineMode`, which when set to `true`, generates documentation that can be run
          on file system (offline, no web server required). Cross domain errors with `file://` origin is fixed with some
          smart tricks so TOC, Nav, Breadcrumb and even the full-text search works.
          We didn't implement a new separate theme but instead added this switch for existing `docfx-plus` theme so that
          the offline version looks and works exactly like online version.
          The problem with docfx bundled `statictoc` theme (besides its ugly looks) is that, it statically inserts TOC to
          every HTML file so it produces very large files expecially for `api` subfolder and it can't run search like our offline mode.

          For example, you can build online version for deploying to your web server:

          ```console
          docfx-plus build -t default,modern,docfx-plus
          ```
          
          and then you can build offline version for bundling in your product zip (works smoothly just like legacy `.chm` files):
          
          ```console
          docfx-plus build -t default,modern,docfx-plus -m _enableOfflineMode -o _site_offline
          ```
          
          Or in your `docfx.json`:
          
          ```json
          "template": [
            "default",
            "modern",
            "docfx-plus"
          ],
          "globalMetadata": {
            "_enableOfflineMode": true
          }
          ```

        - **Added:** Implemented a plugin for the template, which can register itself as a post processor dynamically
          and does some useful tasks like deleting unused files for optimal `_site` folder size, and converting some `.json` files
          to `.js` for being able to support offline mode.
        
        - **Fixed:** Footer background color was not correct in dark mode.
      ]]>
    </PackageReleaseNotes>

    <!--<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>-->

  </PropertyGroup>

  <ItemGroup>
    <!-- Ensure that the plugin is built together with this project -->
    <ProjectReference Include="..\DotMake.DocfxPlus.Plugin\DotMake.DocfxPlus.Plugin.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="DotMake.CommandLine" Version="3.6.0" />
    <PackageReference Include="ReverseMarkdown" Version="4.7.1" />
  </ItemGroup>

  <ItemGroup>
    <!--
      So we have <PackageReference> with ExcludeAssets="All" so that the package reference is not added as a nuget dependency
      in our NuGet package, and with GeneratePathProperty="true" so that we can use <Reference> to reference the DLL from
      the package directly with HintPath.
      https://blog.maartenballiauw.be/post/2020/04/22/referencing-specific-assembly-nuget-package.html
    -->
    <PackageReference Include="docfx" Version="$(DocfxVersion)">
      <GeneratePathProperty>true</GeneratePathProperty>
      <IncludeAssets>None</IncludeAssets>
      <ExcludeAssets>All</ExcludeAssets>
      <PrivateAssets>None</PrivateAssets>
    </PackageReference>
    <Reference Include="docfx">
      <HintPath>$(Pkgdocfx)\tools\$(TargetFramework)\any\docfx.dll</HintPath>
    </Reference>
    <None Include="$(Pkgdocfx)\tools\$(TargetFramework)\any\**">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>False</Visible>
    </None>

    <!-- required as we are referencing docfx as dll, these are needed to prevent conflicts -->
    <PackageReference Include="Docfx.App" Version="$(DocfxVersion)">
      <ExcludeAssets>contentFiles</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Docfx.Dotnet" Version="$(DocfxVersion)">
      <ExcludeAssets>contentFiles</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\templates\**" Exclude="..\templates\_*\**">
      <Link>templates\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <!-- Remove Node.js runtime dependencies that used by playwright -->
  <Target Name="RemoveNodeJsRuntimes" AfterTargets="CopyPlaywrightFilesToOutput">
    <ItemGroup>
      <!--<Content Remove="@(Content)" Condition="$([System.String]::Copy('%(Content.PlaywrightFolder)').Contains('node\'))" />-->
      <Content Remove="@(Content)" Condition="'%(Content.NuGetPackageId)' == 'Microsoft.Playwright'" />
    </ItemGroup>
  </Target>
</Project>
